### ISSUE TITLE
[🕷] selected file opens only when bar loses focus

### ISSUE THREAD

**Issue by b2kdaman** [SaekiRaku/vscode-pin-up#3]
### Steps to reproduce:
Open Pined Files
Click on a file
Click on other tab
Click on pinned file again

**Expected result:**
File opens/tab sets to active
**Actual result:**
Nothing happens

**Comment by SaekiRaku** [comment]
Thanks for your feedback, but it seems nothing I can do to fix this bug for now. Because the API of VSCode [Tree View](https://code.visualstudio.com/api/references/vscode-api#TreeView) only have `onDidChangeSelection` event to locate which file was clicked but no methods were provided to clear the `selected list` to make the event able to trigger again.

I'm going to create an issue to VSCode, hope some functions like above can be added in the future.

**Comment by SaekiRaku** [comment]
I found out a new way to open the files, this issue is fixed. A new version is released to Visual Studio Marketplace. Thanks again.

**Comment by b2kdaman** [comment]
Thank you Saeki!
